version: '3'

services:  
  db:
  # Constrói a partir do Dockerfile na pasta Database
    build: ./database
    container_name: genesis_database
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_PASSWORD"

