version: '3'

services:  
  db:
    build: ./database_cfg
    container_name: genesis_database
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 3306:3306
    env_file:
      - .env
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=root --password='${MYSQL_ROOT_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  api:
    build: .
    container_name: genesis_api
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    env_file:
      - .env
    links:
     - "db:database"
    depends_on:
      db:
        condition: service_healthy
networks:
  default:
    name: Genesis_test